apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loadbalancer
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
  	backend:
  	  serviceName: wwwserver
  	  servicePort: 80
